### ISSUE TITLE
Create OData filter for `null` (`eq` and `ne`)

### ISSUE THREAD

**Issue by lennart-m** [SAP/cloud-sdk-js#1351]
Hi, I have a question about filtering entity sets using the cloud SDK. I would like to  read an entity set, filtering on all entities that have value `null` in a specific field.
So the resulting URL should be:
```http
GET https://myserver/odata/v2/User?$filter=lastName eq null
```
The question also applies to `ne` instead of `eq`.

Unfortunately I am not able to create such filter using the cloud SDK. I tried something like `User.LAST_NAME.equals(null)` but this gives a TS error as only `string`s are allowed.
Also, explicit type casting does not work: `User.LAST_NAME.equals(null as unknown as string)` will create a filter `lastName eq 'null'`.

I might be able to manually set the URL query string for this filter but I would like to use this filter along with other filters, created by the cloud SDK. So does not seem to be an alternative.

Is it possible to achieve this using the cloud SDK?

Thanks a lot,
Lennart

**Comment by artemkovalyov** [comment]
Hey @lennart-m, I'm curious if you have tried supplying a "null" string without casting anything? I believe the mentioned URL also sends just a string to their server for comparison? Does the resulting URL work?

**Comment by lennart-m** [comment]
Hi @artemkovalyov, thanks for your reply. 
The generated URL with `'null'` instead of `null` does not work as it only checks if the field value equals string `'null'`; but I want to check for value `null` (i.e. no string value). If I call `User.LAST_NAME.equals("null")` then I also get the URL `lastName eq 'null'` which is not the one I need. Also, filtering on empty string is not interpreted as filtering on `null` by the remote system.

I found this to be the code that converts my `null` to `'null'` (lines 39 to 41):
![image](https://user-images.githubusercontent.com/20302675/121513504-33e3d980-c9eb-11eb-9f08-7183c1261701.png)

As it's a `Edm.String` field the `'null'` string then gets converted once more so the resulting URL contains the single quotes:
![image](https://user-images.githubusercontent.com/20302675/121515263-4bbc5d00-c9ed-11eb-9440-9c34fec2f346.png)

The OData specification states that there is a `null` literal. It seems like the cloud SDK does not correctly handle this.
V2:
https://www.odata.org/documentation/odata-version-2-0/uri-conventions/#:~:text=instead%2C%20there%20is%20a%20null%20literal%20which%20can%20be%20used%20in%20comparisons.
V4:
https://www.oasis-open.org/committees/download.php/58261/NullInOData.html#:~:text=instead%2C%20there%20is%20a%20null%20literal%20that%20can%20be%20used%20in%20comparisons.

In my opinion there should be special handling of the `null` literal.

I will try to find a workaround, maybe creating a custom field of different `Edm` type will help.

**Comment by jjtang1985** [comment]
Hi @lennart-m ,

I can reproduce the type error and I created a backlog item.

Please share your timeline, if possible.

Thank you very much.

Best regards,
Junjie

**Comment by artemkovalyov** [comment]
Thanks for answering @jjtang1985 and clearing things up a lot @lennart-m. After knowing your deadlines we'll prioritize fixing this bug.

**Comment by lennart-m** [comment]
Hi @jjtang1985 and @artemkovalyov, thank you very much for handling this.
The application I'm working on will probably go live within a few months.
I am now implementing a workaround by not writing null values to the required fields in the remote system so I can filter properly. So there is no urgency.

By the way, the remote system is SAP SuccessFactors so this issue will perhaps come up more often; a workaround for this is not that easy due to the behavior of SuccessFactors when filtering (a filter on `lastName ne 'name'` will not find entities with `lastName=null` although this would be semantically correct).

Sincerely,

Lennart

**Comment by jjtang1985** [comment]
Hi @lennart-m ,

the `null` is now supported like this example:
`TestEntity.STRING_PROPERTY.equals(null);`.

To test it, you need to follow the steps:
1. use the `canary` version of the `@sap-cloud-sdk/generator` to generate your clients again. 
2. use your new client with the `canary` version of the `@sap-cloud-sdk/core` for your tests.

Please let me know if there are still questions.
We might release a new stable version next week.

Best regards,
Junjie

**Comment by jjtang1985** [comment]
Hi @lennart-m ,

we have released [1.47.0](https://github.com/SAP/cloud-sdk-js/releases/tag/v1.47.0), please try the latest version.

I'll close this ticket and please reopen if you have questions.

Best regards,
Junjie

**Comment by lennart-m** [comment]
Hi, I just tried this using the new version 2 of the cloud SDK. The issue still persists (or persists again?)
Filtering using `field.equals(null)` results in filter parameter `field eq 'null'`.

Should I open a new issue?

Thanks!
